image: lamhq/node-pipeline:latest

pipelines:
  custom:
    # Deploy to test env (manually triggered)
    deploy-to-test:
      - step:
          name: Deploy
          deployment: Test
          script:
            - yarn run deploy
          services:
            - docker

  tags:
    # deploy to test environment when a release tag is created
    "*":
      - step:
          name: Deploy
          deployment: Test
          script:
            - yarn run deploy
          services:
            - docker

