name: Deploy

on:
  push:
    # tags:
    #   - v*
    branches:
      - master

jobs:
  deploy_to_production:
    name: Deploy to Production
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.SERVICE_ACCOUNT_KEY }}'
          projectId: '${{ secrets.PROJECT_ID }}'
          channelId: live

      - name: Get current version
        id: npm_package_version
        uses: Saionaro/extract-package-version@v1.0.6

      - name: Create deploy tag
        run: |-
          git tag -f v${{ steps.npm_package_version.outputs.version }}
          git tag -f prod
          git push -f --tags