name: Deploy the application

on:
  push:
    branches: [main]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  deploy_to_production:
    name: Deploy to production
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.1

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Build the app
        run: |
          echo '${{secrets.ENV_VARS}}' > .env
          pnpm install --prod=false
          pnpm run build

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{vars.CD_ROLE_ARN}}
          aws-region: ${{vars.AWS_REGION}}

      - name: Set up Terraform CLI for CI server
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.10.3'

      - name: Init Terraform
        working-directory: infra
        run: |
          echo '${{secrets.TF_BACKEND_CONFIG}}' > backend.tfvars
          terraform init -backend-config=backend.tfvars -reconfigure

      - name: Deploy the app
        working-directory: infra
        run: |
          terraform workspace select default
          echo '${{secrets.TF_VARS}}' > params.tfvars
          terraform apply --auto-approve -var-file="params.tfvars"
