name: Deploy to Preview Channel
on:
  pull_request:
    branches:
      - master
jobs:
  build_preview:
    name: Build Preview
    environment: preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Deploy preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.SERVICE_ACCOUNT_KEY }}'
          projectId: '${{ secrets.PROJECT_ID }}'
